import React from 'react';
import type { NextPage } from 'next';
import Head from 'next/head';
import styles from '../styles/Home.module.scss';
import { getUsersAction } from '@/redux/Actions/UserAction';
import { useAppSelector, useAppDispatch } from '@/hooks/useRedux';

const Home: NextPage = () => {
  const dispatch = useAppDispatch();

  const selector = useAppSelector((state) => ({
    users: state.userReducer.getUsersSuccess,
    loading: state.userReducer.getUsersLoading,
  }));

  const { users, loading } = selector;

  React.useEffect(() => {
    dispatch(getUsersAction());
  }, [dispatch]);

  return (
    <div className={styles.home}>
      <Head>
        <title>UPG Back Office</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className="text-3xl font-bold underline" data-testid="greeting">
        List of users
      </h1>
      {!loading && users && users.length > 0 && (
        <ul>
          {users.map((item, itemKey) => (
            <li key={itemKey}>{item.username}</li>
          ))}
        </ul>
      )}
      {loading && (
        <div className="font-bold" data-testid="loading">
          Loading ...
        </div>
      )}
    </div>
  );
};

export default Home;
